name: Calcular 2 + 2

on:
  workflow_dispatch:

jobs:
  calcular:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar data e hora do push
        run: echo "üïí Data e hora: $(date)"

      - name: Definir vari√°vel com resultado
        run: |
          resultado=$((2 + 2))
          echo "O resultado de 2 + 2 √© $resultado"
          echo "resultado=$resultado" >> $GITHUB_ENV

      - name: Exibir vari√°vel armazenada
        run: echo "A vari√°vel resultado √© $resultado"
        env:
          resultado: ${{ env.resultado }}
